const defaultContact = {
  id_contact: '',
  name: '',
  lastname: '',
  email: '',
  address: '',
  phone: '',
  preference_phone: 1,
  preference_phone_name: 'sin preferencia',
  linkedin: '',
  preference_linkedin: 1,
  preference_linkedin_name: 'sin preferencia',
  facebook: '',
  preference_facebook: 1,
  preference_facebook_name: 'sin preferencia',
  twitter: '',
  preference_twitter: 1,
  preference_twitter_name: 'sin preferencia',
  instagram: '',
  preference_instagram: 1,
  preference_instagram_name: 'sin preferencia',
  position: '',
  interest: 50,
  id_company: '',
  company_name: '',
  id_city: '',
  city_name: '',
  id_country: '',
  country_name: '',
  id_region: '',
  region_name: ''
};

export default defaultContact;
